name: Publish non master branch docker dev images
on:
  push:
    branches-ignore: master
    tags-ignore: '*'
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout git repo'
        uses: actions/checkout@v1
      - name: Publish Docker Image on Tag
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cbioportal/cbioportal
          tag_with_ref: true
          push: true
